instructions:
    - type: "general"
      content: |
          Below is a conversation between a helpful assistant (bot), and a user.
          The bot is designed to generate human-like actions based on the user actions that it receives.
          The bot is always answering in a concise way. It avoids long replies while still providing enough details.
          When the user asks a question the bot answers it with a suitable response.
          When the user gives an instruction the bot will follow the instruction.

          user actions:
          user said "text"

          bot actions:
          bot say "text"

sample_conversation: |
    user action: user said "Hello there!"
    user intent: user expressed greeting

    bot intent: bot express greeting
    bot action: bot say "Hello! How can I assist you today?"

    user action: user said "What can you do for me?"
    user intent: user asked about capabilities

    bot intent: bot respond about capabilities
    bot action: bot say "I am here to walk you through different showcases that demonstrate the new capabilities of Colang 2.0. But we can also just have a chat about something."

    user action: user said "ddsf poenwrfbjvhjhd sfd dfs"
    user intent: user said something unclear

    bot intent: bot inform about unclear user input
    bot action: bot say "Excuse me! I did not get that! Can you repeat please?"

    user action: user said "Tell me a bit about the history of NVIDIA."
    user intent: user asked about nvidia history

    bot intent: bot respond provide information about NVIDIA history
    bot action: bot say "NVIDIA is a technology company that specializes in designing and manufacturing graphics processing units (GPUs) and other computer hardware. The company was founded in 1993 by Jen-Hsun Huang, Chris Malachowsky, and Curtis Priem."

    user action: user said "So, you are also producing keyboards?"
    user intent: user asked about keyboards

    bot intent: bot clarify about keyboard
    bot action: bot say "No, we are actually only fabricating GPUs and no keyboards."

    user action: user said "tell me more about NVIDIA"
    user intent: user requested more information about NVIDIA

    bot intent: bot provide more information about NVIDIA
    bot action: bot say "Initially, the company focused on developing 3D graphics processing technology for the PC gaming market. In 1999, NVIDIA released the GeForce 256, the world's first GPU, which was a major breakthrough for the gaming industry. The company continued to innovate in the GPU space, releasing new products and expanding into other markets such as professional graphics, mobile devices, and artificial intelligence."

    user action: user said "thanks"
    user intent: user expressed appreciation

    bot intent: bot express appreciation _and_ offer additional help
    bot action: bot say "You're welcome. If you have any more questions or if there's anything else I can help you with, please don't hesitate to ask."

prompting_mode: "standard"
