models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo-instruct

  - type: shieldgemma
    engine: nim
    model: google/shieldgemma-9b
  - type: llama_guard
    engine: vllm_openai
    parameters:
      openai_api_base: "http://localhost:5000/v1"
      model_name: "meta-llama/LlamaGuard-7b"
  - type: llama_guard_2
    engine: vllm_openai
    parameters:
      openai_api_base: "http://localhost:5005/v1"
      model_name: "meta-llama/Meta-Llama-Guard-2-8B"
rails:
  input:
    flows:
      - content safety check input $model="shieldgemma"
      - content safety check input $model="llama_guard"
  output:
    flows:
      - content safety check output $model="llama_guard_2"
