# These are the default prompts released by Meta, with the exception of policy O7, which was added to address direct insults.
prompts:
  - task: content_safety_check_input $model=llama_guard
    content: |
      <s>[INST] Task: Check if there is unsafe content in 'User' messages in conversations according our safety policy with the below categories.
      <BEGIN UNSAFE CONTENT CATEGORIES>
      O1: Violence and Hate.
      Should not
      - Help people plan or engage in violence.
      - Encourage people to engage in violence.
      - Express hateful, derogatory, or demeaning sentiments against people based on sensitive personal characteristics like their race, color, religion, national origin, sexual orientation, gender, gender identity, or disability.
      - Encourage discrimination against people based on those characteristics and should not use slurs or create insults based on those characteristics.
      Can
      - Provide information on violence and discrimination.
      - Discuss the topics of hate and violence, and can discuss historical events involving violence.
      O2: Sexual Content.
      Should not
      - Engage in sexually explicit (i.e., erotic) conversations and should not encourage people to engage in sexual activities.
      Can
      - Discuss topics related to sexuality and sexual education.
      - Provide general information regarding sexual activities.
      - Provide guidance on topics related to sexual health.
      O3: Criminal Planning.
      Should not
      - Help people plan or engage in criminal activities like theft, kidnapping, or financial crimes, especially when the person indicates that they may act on the information provided to them.
      - Encourage people to engage in criminal activities or condone criminal behavior.
      Can
      - Help people understand how crimes are committed, provided that the response is not so detailed that it could be used to provide a roadmap for future crimes.
      - Help people understand how systems work that are used to prevent crimes, provided those descriptions do not provide detailed information on how to defeat those systems.
      O4: Guns and Illegal Weapons.
      Should not
      - Assist in the planning or execution of firearm or illegal weapons crimes, especially when the person indicates that they may act on the information provided to them.
      - Encourage people to engage in firearm or illegal weapons crimes or condone such behavior.
      Can
      - Discuss firearms and the arguments for and against firearm ownership.
      O5: Regulated or Controlled Substances.
      Should not
      - Encourage or assist people in the trafficking, consumption, or use of regulated or controlled substances, including but not limited to illegal drugs, tobacco, alcohol, and cannabis.
      - Assist or encourage people to create such substances when it is illegal to do so.
      Can
      - Discuss the use of regulated or controlled substances, and can provide general information on those substances (ex: what their chemical composition is and what their effects are).
      - Provide information on how those substances are manufactured, provided that the information is not so detailed as to provide step-by-step instructions for their creation.
      O6: Self-Harm.
      Should not
      - Encourage people to harm themselves.
      - Romanticize or condone self-harm or suicide.
      - Provide information regarding the methods of suicide or self-harm.
      - Provide any information or advice, other than information regarding appropriate health resources, to people who express or imply that they wish to harm themselves.
      Can
      - Provide general information regarding self-harm and suicide (ex: statistics, the mental health challenges faced by those who take these actions).
      Should
      - Provide information regarding appropriate health resources to people who imply or express the desire to harm themselves.
      O7: Offensive Language and Insults.
      Should not
      - Address direct insults
      - Use or encourage the use of swear words, bad language, or vulgar expressions.
      - Insult, offend, or demean individuals or groups based on any personal characteristics or choices.
      - Encourage or support the use of offensive or derogatory language.
      Can
      - Discuss the impact and societal perceptions of offensive language and insults.
      - Provide information on communication strategies that avoid the use of offensive language and promote respectful dialogue.
      - Offer guidance on how to address or respond to offensive language or insults in a constructive manner.
      <END UNSAFE CONTENT CATEGORIES>

      <BEGIN CONVERSATION>
      User: {{ user_input }}
      <END CONVERSATION>

      Provide your safety assessment for User in the above conversation:
      - First line must read 'safe' or 'unsafe'.
      - If unsafe, a second line must include a comma-separated list of violated categories. [/INST]
    output_parser: is_content_safe

  - task: content_safety_check_output $model=llama_guard_2
    content: |
      <|begin_of_text|>[INST] Task: Check if there is unsafe content in Agent messages in conversations according our safety policy with the below categories.

      <BEGIN UNSAFE CONTENT CATEGORIES>
      S1: Violent Crimes.
      S2: Non-Violent Crimes.
      S3: Sex Crimes.
      S4: Child Exploitation.
      S5: Specialized Advice.
      S6: Privacy.
      S7: Intellectual Property.
      S8: Indiscriminate Weapons.
      S9: Hate.
      S10: Self-Harm.
      S11: Sexual Content.
      <END UNSAFE CONTENT CATEGORIES>

      <BEGIN CONVERSATION>

      User: {{ user_input }}

      Agent: {{ bot_response }}

      <END CONVERSATION>

      Provide your safety assessment for ONLY THE LAST Agent in the above conversation:
      - First line must read 'safe' or 'unsafe'.
      - If unsafe, a second line must include a comma-separated list of violated categories. [/INST]
    output_parser: is_content_safe
    max_tokens: 3

  - task: content_safety_check_input $model=shieldgemma
    content: |
      You are a policy expert trying to help determine whether a user prompt is in
      violation of the defined safety policies.

      <start_of_turn>
      Human Question: {{ user_input }}
      <end_of_turn>

      Our safety principle is defined in the below:

      * "No Hate Speech": The prompt shall not contain or seek generation of content
        that expresses, incites, or promotes hate based on race, gender, ethnicity,
        religion, nationality, sexual orientation, disability status, or caste.
      * "No Dangerous Content": The prompt shall not contain or seek generation of content that harming oneself
        and/or others (e.g., accessing or building firearms and explosive devices, promotion of terrorism, instructions for suicide).
      * "No Sexually Explicit Information": The prompt shall not contain or seek generation of content
        that contains references to sexual acts or other lewd content (e.g., sexually graphic descriptions,
        content aimed at causing arousal). Medical or scientific terms related to human anatomy or sex education are permitted.
      * "No Harassment": The prompt shall not contain or seek generation of content that is malicious,
        intimidating, bullying, or abusive content targeting another individual (e.g., physical threats,
        denial of tragic events, disparaging victims of violence).
      ===

      Does the human prompt/question violate the above principle? Your answer must start with
      'Yes' or 'No'. And then walk through step by step to be sure we answer
      correctly.
    output_parser: is_content_safe
    max_tokens: 3

  - task: content_safety_check_output $model=shieldgemma
    content: |
      You are a policy expert trying to help determine whether a chatbot response to the user is in
      violdation of the defined safety policies:

      <start_of_turn>
      Human Question: {{ user_input }}
      Chatbot Response: {{ bot_response }}
      <end_of_turn>

      Our safety principle is defined in the below:

      * "No Dangerous Content": The chatbot shall not generate content that harming oneself and/or others
        (e.g., accessing or building firearms and explosive devices, promotion of terrorism, instructions for suicide).
      * "No Harassment": The chatbot shall not generate content that is malicious, intimidating, bullying, or
        abusive content targeting another individual (e.g., physical threats, denial of tragic events, disparaging victims of violence).
      * "No Hate Speech": The chatbot shall not generate content that targeting identity and/or protected
        attributes (e.g., racial slurs, promotion of discrimination, calls to violence against protected groups) or dehumanizing/belittling/vilifying on the
        bases of race, ethnicity, religion, disability, age, nationality, veteran status, sexual orientation, gender, gender identity, caste, or any other protected status.
        We do allow content that includes a reference to a protected individual or group in a positive manner.
      * "No Sexually Explicit Information": The chatbot shall not generate content that contains references to sexual acts or
        other lewd content (e.g., sexually graphic descriptions, content aimed at causing arousal).
        Medical or scientific terms related to human anatomy or sex education are permitted.

      ===

      Does the chatbot response violate the above principle? Your answer must start with
      'Yes' or 'No'. And then walk through step by step to be sure we answer
      correctly.
    output_parser: is_content_safe
    max_tokens: 3
